### PR TITLE
Added support to Ray Tune and Custom Models implementation

### PR DESCRIPTION
**Pull request by FFede0**
- Closed open points from #2 and updated the TuningExperiment by:
    - Adding a `Tuner` class following the model of `Algorithm`
    - Fixing issues with coherence checks when suggested keys are tuned and depend on each other
- Imported the custom models features from #3 
- Added the SAC algorithm implementation from #6 

#### Open points (to be addressed before merging into main)
- [ ] when the `duration_unit` for sampling experience is `episodes`, tune should consider a quniform sampling strategy to avoid picking values that do not correspond to a whole episode
- [ ] the warning message concerning the size of the custom network and `hiddens` in `DQNConfigGenator` should be updated by actually checking the compatibility
- [ ] restoring a `TuningExperiment` from a checkpoint fails if HyperOpt is used as search algorithm. Investigate to decide whether to warn the user or if the issue can be fixed

### CODE REVIEW

**Review by wakephul — COMMENTED** [review]
I tried running the system following the available READMEs.
Some notes from my side:
- when opening the config_files folder, I see the regression tests and I'm somewhat confused;
- for example, the ray_config_dqn template is different than what I find inside regression_tests/dqn: which should be used if I want to copy/paste and change? my guess is the template. however, inside the regression_test I see that the json does not include the framework; so, can it be omitted? --> should have a list of mandatory parameters
- is there a parameter to set to say that we are expert users and want to specify the protected keywords by hand?
- it is unclear to me what points 2 and 3 of https://github.com/FFede0/RL4CC?tab=readme-ov-file#how-to-start-a-training-experiment are asking me to do (?) does this imply that I should have imported RL4CC as a library in my project? it is kind of explained in the following section, but I might not ever get to that if I don't have a custom env (?)
- I would add a requirements file (?)
- I get PermissionError: [Errno 13] Permission denied: '/tmp/ray/session_2024-05-23_09-48-24_349873_3183752/node_ip_address.json.lock'

**Comment by FFede0** [comment]
Some point-by-point answers:

> - when opening the config_files folder, I see the regression tests and I'm somewhat confused;
> 
> - for example, the ray_config_dqn template is different than what I find inside regression_tests/dqn: which should be used if I want to copy/paste and change? my guess is the template. however, inside the regression_test I see that the json does not include the framework; so, can it be omitted? --> should have a list of mandatory parameters

Regression tests are still under development, so they are not really supposed to be used at the moment. When they will be ready, I'll add a section to the readme (I will add a section to say they are TBA, though, to avoid confusion).
As mentioned in the README, you can use the template files as starting points (while there are examples directly written in the README for what concerns the environment/experiment configuration files).

 
> - is there a parameter to set to say that we are expert users and want to specify the protected keywords by hand?

No:
- if you use them & do not use any suggested keys, you're supposed to be expert (if not, too bad)
- if you use them & simultaneously use any suggested keys, you get an error
 
> - I would add a requirements file (?)

We may, but at the moment we're performing the tests with many different ray versions, so not sure what to write in that file...I'll think about it
 
> - I get PermissionError: [Errno 13] Permission denied: '/tmp/ray/session_2024-05-23_09-48-24_349873_3183752/node_ip_address.json.lock'

While running what?

**Comment by FFede0** [comment]
About this:

> > it is unclear to me what points 2 and 3 of https://github.com/FFede0/RL4CC?tab=readme-ov-file#how-to-start-a-training-experiment are asking me to do (?) does this imply that I should have imported RL4CC as a library in my project? it is kind of explained in the following section, but I might not ever get to that if I don't have a custom env (?)

I've added the import line to the code, but I'm not sure whether your concern is addressed...yes, you should import `TrainingExperiment` before using it, if that's the question

**Review by wakephul — APPROVED** [review]
At this point, the PR to develop looks good to me.
Open points (to be addressed before merging into main)
- [ ] when the duration_unit for sampling experience is episodes, tune should consider a quniform sampling strategy to avoid picking values that do not correspond to a whole episode
- [ ]  the warning message concerning the size of the custom network and hiddens in DQNConfigGenator should be updated by actually checking the compatibility
- [ ]  restoring a TuningExperiment from a checkpoint fails if HyperOpt is used as search algorithm. Investigate to decide whether to warn the user or if the issue can be fixed
- [ ] make sure to clarify how ray.init + custom model registration work

**Pull request merged**
